services:
  portfolio:
    image: hq.local:5000/portfolio
    restart: unless-stopped
    ports:
      - 9991:80
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: npm_network
